version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=crack_jugadas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:supersecretpassword@db:5432/crack_jugadas_db
      - FRONTEND_URL=http://localhost:3000
      - ADMIN_URL=http://localhost:3001
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080

volumes:
  postgres_data:
